main: dk.muj.derius.blocks.DeriusBlocks
name: Derius-Blocks
version: 1.0_beta
#website: http://muj.dk/Derius
authors: [Madus, Ulumulu1510]
description: §eDerius-Blocks keeps track of placed blocks to be used by Derius
softdepend: [Derius-Core]
load: startup
